sudo: required

language: python
python:
- '3.6'

env:
#- DJANGO_VERSION=2.1.4
#- DJANGO=1.11.2
- DJANGO=2.1.4
-
install:
- pip install --upgrade pip
- pip install -q django==$DJANGO
- pip install -r requirements.txt
#- pip install -q Django==$DJANGO_VERSION

script:
- python manage.py test
- python -m pytest -v feedback/tests.py


deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app:
#    master: $HEROKU_APP_NAME
    lab_1: $HEROKU_APP_NAME

  #on:
    #repo: HapCuji/DSIP
  #run: "rake db:migrate"
    
notifications:
  email: false
