language: python
python:
- '3.7'

env:
- DJANGO_VERSION=2.1.4
- DJANGO=1.11.2

install:
- pip install -q django==$DJANGO
- pip install -q Django==$DJANGO_VERSION

script:
- python manage.py test
- python -m pytest -v feedback/tests.py


deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app: 
    master: $HEROKU_APP_NAME
  #on:
    #repo: HapCuji/DSIP
  #run: "rake db:migrate"
    
notifications:
  email: false
