version: '3'
# Список наших сервисов (контейнеров)

services:
    apache:
        image: httpd:2.4
        volumes:
          - ./src:/usr/local/apache2/htdocs
          - ./hosts/httpd.conf:/usr/local/apache2/conf/httpd.conf
        depends_on:
          - php

    nginx:
        image: nginx:1.13
        ports:
          - 80:80
        volumes:
          - ./src:/usr/local/apache2/htdocs #./www/agregator_ser/ : /var/www/agregator_ser/
          - ./hosts/nginx.conf:/etc/nginx/nginx.conf # /hosts/agregator_ser.conf:/etc/nginx/agregator_ser.conf
        depends_on:
          - apache

    php:
        build:
          ./php
        volumes:
          - ./src:/usr/local/apache2/htdocs # ./www/agregator_ser/:/var/www/agregator_ser/
          - ./php/php.ini:/usr/local/etc/php/php.ini
        depends_on:
          - mariadb
    
    mariadb:
        image: mysql:5.5
        #command: --default-authentication-plugin=mysql_native_password
        #restart: always
        volumes:
            - ./mysql:/var/lib/mysql8
        environment:
             MYSQL_ROOT_PASSWORD: qwerty

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
          - mariadb:db
        ports:
          - 8765:80
        environment:
            MYSQL_USERNAME: root
            MYSQL_ROOT_PASSWORD: examplepass
            PMA_HOST: mariadb
        depends_on:
          - mariadb

# services:
# #
#     app:
#         build: ./images/php
#         working_dir: /php/
#         volumes:
#             - ./www/agregator_ser/:/var/www/agregator_ser/
#         expose:
#             - 9000
#         ports:
#           - "8100:80"
#         links:
#             - db

#     nginx:
#         image: nginx:latest
#         ports:
#             - "80:80"
#         volumes:
#             - ./www/agregator_ser/:/var/www/agregator_ser/
#             - /hosts/agregator_ser.conf:/etc/nginx/agregator_ser.conf
#         links:
#             - app

#     db:
#         image: mysql:5.7
#         volumes:
#             - /var/lib/mysql
#         ports:
#             - "3306:3306"
#         environment:
#             MYSQL_ROOT_PASSWORD: secret
#             MYSQL_DATABASE: test_db
#             MYSQL_USER: devuser
#             MYSQL_PASSWORD: devpass

